/**
 * 道元纪・原创敌人配置
 * 由 .tres 自动转换生成
 */
export interface DaoyuanEnemy {
  enemyId: string;
  unitName: string;
  level: number;
  elemLevel: number;
  hp: number;
  maxHp: number;
  mp: number;
  maxMp: number;
  atk: number;
  def: number;
  spd: number;
  critRate: number;
  critDmg: number;
  element: number;
  aiMode: number;
  skills: string[];
  expReward: number;
  isBoss: boolean;
}

export const DAOYUAN_ENEMIES: DaoyuanEnemy[] = [
  {
    enemyId: 'bandit_chief',
    unitName: '山贼头目',
    level: 3,
    elemLevel: 2,
    hp: 150,
    maxHp: 150,
    mp: 30,
    maxMp: 30,
    atk: 18,
    def: 6,
    spd: 7,
    critRate: 0.04,
    critDmg: 1.5,
    element: 0,
    aiMode: 2,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'dao_guardian',
    unitName: '道源守护者',
    level: 10,
    elemLevel: 5,
    hp: 8000,
    maxHp: 8000,
    mp: 2000,
    maxMp: 2000,
    atk: 350,
    def: 120,
    spd: 30,
    critRate: 0.1,
    critDmg: 2.5,
    element: 2,
    aiMode: 3,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'deep_dragon',
    unitName: '深海蛟龙',
    level: 6,
    elemLevel: 3,
    hp: 800,
    maxHp: 800,
    mp: 300,
    maxMp: 300,
    atk: 60,
    def: 30,
    spd: 13,
    critRate: 0.04,
    critDmg: 1.7,
    element: 2,
    aiMode: 2,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'flame_bird',
    unitName: '赤焰鸟',
    level: 3,
    elemLevel: 2,
    hp: 100,
    maxHp: 100,
    mp: 40,
    maxMp: 40,
    atk: 20,
    def: 5,
    spd: 12,
    critRate: 0.03,
    critDmg: 1.4,
    element: 3,
    aiMode: 1,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'golden_core_devil',
    unitName: '金丹魔修',
    level: 5,
    elemLevel: 3,
    hp: 600,
    maxHp: 600,
    mp: 200,
    maxMp: 200,
    atk: 45,
    def: 20,
    spd: 10,
    critRate: 0.05,
    critDmg: 1.6,
    element: 3,
    aiMode: 2,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'ice_wraith',
    unitName: '冰晶妖',
    level: 4,
    elemLevel: 2,
    hp: 200,
    maxHp: 200,
    mp: 60,
    maxMp: 60,
    atk: 25,
    def: 10,
    spd: 9,
    critRate: 0.03,
    critDmg: 1.5,
    element: 2,
    aiMode: 1,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'magma_beast',
    unitName: '熔岩巨兽',
    level: 7,
    elemLevel: 4,
    hp: 1200,
    maxHp: 1200,
    mp: 300,
    maxMp: 300,
    atk: 100,
    def: 50,
    spd: 7,
    critRate: 0.03,
    critDmg: 1.8,
    element: 3,
    aiMode: 1,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'shadow_scout',
    unitName: '幽影殿探子',
    level: 4,
    elemLevel: 2,
    hp: 180,
    maxHp: 180,
    mp: 80,
    maxMp: 80,
    atk: 30,
    def: 12,
    spd: 11,
    critRate: 0.05,
    critDmg: 1.6,
    element: 3,
    aiMode: 2,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'stone_demon',
    unitName: '石魔',
    level: 2,
    elemLevel: 1,
    hp: 90,
    maxHp: 90,
    mp: 15,
    maxMp: 15,
    atk: 10,
    def: 8,
    spd: 4,
    critRate: 0.01,
    critDmg: 1.4,
    element: 4,
    aiMode: 1,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'tribulation_beast',
    unitName: '天劫雷兽',
    level: 9,
    elemLevel: 5,
    hp: 5000,
    maxHp: 5000,
    mp: 1200,
    maxMp: 1200,
    atk: 220,
    def: 80,
    spd: 25,
    critRate: 0.08,
    critDmg: 2.2,
    element: 0,
    aiMode: 3,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'venom_snake',
    unitName: '毒蛇',
    level: 2,
    elemLevel: 1,
    hp: 45,
    maxHp: 45,
    mp: 20,
    maxMp: 20,
    atk: 12,
    def: 2,
    spd: 10,
    critRate: 0.05,
    critDmg: 1.5,
    element: 1,
    aiMode: 1,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'void_messenger',
    unitName: '寂灭道使者',
    level: 7,
    elemLevel: 4,
    hp: 1500,
    maxHp: 1500,
    mp: 500,
    maxMp: 500,
    atk: 90,
    def: 45,
    spd: 18,
    critRate: 0.06,
    critDmg: 1.8,
    element: 0,
    aiMode: 3,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'void_shade',
    unitName: '虚空魔影',
    level: 8,
    elemLevel: 4,
    hp: 3000,
    maxHp: 3000,
    mp: 800,
    maxMp: 800,
    atk: 150,
    def: 60,
    spd: 20,
    critRate: 0.07,
    critDmg: 2.0,
    element: 4,
    aiMode: 3,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'wild_wolf',
    unitName: '野狼',
    level: 1,
    elemLevel: 1,
    hp: 50,
    maxHp: 50,
    mp: 10,
    maxMp: 10,
    atk: 8,
    def: 3,
    spd: 6,
    critRate: 0.02,
    critDmg: 1.3,
    element: 0,
    aiMode: 0,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
  {
    enemyId: 'wood_spirit',
    unitName: '古木妖灵',
    level: 5,
    elemLevel: 3,
    hp: 400,
    maxHp: 400,
    mp: 120,
    maxMp: 120,
    atk: 35,
    def: 15,
    spd: 8,
    critRate: 0.03,
    critDmg: 1.5,
    element: 1,
    aiMode: 1,
    skills: [],
    expReward: 10,
    isBoss: false,
  },
];
